# -*- coding: utf-8 -*-
"""Excel_姓名統計工具.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpOpCs4NbBBGDP-AbACxoLRZwXjTR4z1

# 📊 Excel 姓名統計自動化工具（工作表1 ➜ 工作表2）
使用者只需上傳含「工作表1」的 Excel 檔，系統會自動：
- 擷取 C 欄資料中「-」後的姓名
- 統計每個姓名出現次數
- 產生新的「工作表2」：依照次數由多到少排序
- 最後自動加入總計行

⚡ 一鍵完成並匯出 Excel 結果報表

---
"""

# Step 1：安裝套件（第一次使用需執行）
!pip install pandas openpyxl

"""## Step 2：上傳你的 Excel 檔案（必須包含名為「工作表1」的工作表）"""

from google.colab import files
uploaded = files.upload()

"""## Step 3：擷取、統計、建立新報表"""

import pandas as pd
import io

# 取得上傳的檔案名稱
file_name = list(uploaded.keys())[0]
xlsx = pd.ExcelFile(io.BytesIO(uploaded[file_name]))

# 讀取工作表1
df1 = xlsx.parse('工作表1')

# 擷取 C 欄從第 2 列開始的資料
data = df1.iloc[1:, 2].dropna().astype(str)
names = data.str.extract(r'-(.+)$')[0].str.strip()

# 統計並排序
summary = names.value_counts().reset_index()
summary.columns = ['姓名', '次數']

# 加總
total = summary['次數'].sum()
summary.loc[len(summary)] = ['總計', total]

"""## Step 4：產出新的 Excel 並下載"""

output_file = "產出報表.xlsx"
with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
    summary.to_excel(writer, sheet_name='工作表2', startrow=2, startcol=1, index=False)
    ws = writer.sheets['工作表2']
    ws['B2'] = '姓名'
    ws['C2'] = '次數'

# 下載檔案
files.download(output_file)