name: Build Windows EXE

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if (Test-Path "requirements.txt") {
          pip install -r requirements.txt
        }

    - name: Build EXE
      run: |
        pyinstaller --noconfirm --windowed --onedir "excel_name_tool.py"

    - name: Zip output folder (clean name)
      shell: pwsh
      run: |
        $source = Join-Path -Path "dist" -ChildPath "excel_name_tool"
        $destination = "dist/excel_name_tool.zip"
        Compress-Archive -Path "$source/*" -DestinationPath $destination

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/excel_name_tool.zip
