name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl msoffcrypto-tool

    - name: Build EXE using PyInstaller
      run: pyinstaller --noconfirm --windowed --onedir excel_name_tool.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: excel_name_tool_dist
        path: dist/excel_name_tool/
