name: Build Windows EXE

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if exist requirements.txt pip install -r requirements.txt

    - name: Build EXE
      run: |
        pyinstaller --noconfirm --windowed --onedir "excel_姓名統計工具.py"

    - name: Zip output folder
      run: |
        Compress-Archive -Path "dist\\excel_姓名統計工具\\*" -DestinationPath "dist\\excel_姓名統計工具.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe
        path: dist/excel_姓名統計工具.zip
