name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      shell: pwsh
      run: |
        pyinstaller --noconfirm --windowed --onedir excel_name_tool.py --hidden-import=openpyxl

    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: excel_name_tool_dist
        path: dist/excel_name_tool/
